### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by seanpianka** [Yoeori/async-oncecell#3]
Hello,

Could you clarify the benefits of this crate over an alternative like [async_once](https://crates.io/crates/async_once)?

Thanks!

**Comment by Yoeori** [comment]
Hey Sean,

Thanks for taking a time to look into this crate! As for the difference between async_once: I hadn't heard of this crate before, and having taken a look its features seem to be mostly the same but a bit more limited. Async_once mainly features a sort of Lazy which is initialized with its supplied initializer on first request, however this crate also contains a OnceCell which is initialized only once with the given initializer on each request (the initializer can thus be set at a later point). This crate has been designed to conform as much to the given api of [once_cell](https://crates.io/crates/once_cell) and the currently unstable [std::lazy](https://doc.rust-lang.org/nightly/std/lazy/index.html).

I also notice that the documentation mainly talks about its usage in lazy_static, and I'm not sure if its meant to be used outside of that environment. This crate is meant to be a general implementation which should work just about anywhere you would need it.

**Comment by danieldg** [comment]
In particular, async_once requires `&'static AsyncOnce<T>`, and OnceCell is useful in structures that can be freed.

**Comment by danieldg** [comment]
Note that https://crates.io/crates/double-checked-cell-async provides the same API as OnceCell.
